//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 10:04:40 PM CEST 
//


package se.aceone.mediatek.linkit.xml.config;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.aceone.mediatek.linkit.xml.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PackageinfoTargetconfigMem_QNAME = new QName("", "mem");
    private final static QName _PackageinfoTargetconfigSupportbg_QNAME = new QName("", "supportbg");
    private final static QName _PackageinfoTargetconfigUserfont_QNAME = new QName("", "userfont");
    private final static QName _PackageinfoTargetconfigScreenrotate_QNAME = new QName("", "screenrotate");
    private final static QName _PackageinfoTargetconfigAutoadaptable_QNAME = new QName("", "autoadaptable");
    private final static QName _PackageinfoTargetconfigUsesysmemory_QNAME = new QName("", "usesysmemory");
    private final static QName _PackageinfoTargetconfigSysdisk_QNAME = new QName("", "sysdisk");
    private final static QName _PackageinfoTargetconfigPush_QNAME = new QName("", "Push");
    private final static QName _PackageinfoTargetconfigPushID_QNAME = new QName("", "PushID");
    private final static QName _PackageinfoTargetconfigPushSenderID_QNAME = new QName("", "PushSenderID");
    private final static QName _PackageinfoTargetconfigAutostart_QNAME = new QName("", "autostart");
    private final static QName _PackageinfoTargetconfigTransferImg_QNAME = new QName("", "TransferImg");
    private final static QName _PackageinfoTargetconfigIdleshortcut_QNAME = new QName("", "idleshortcut");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.aceone.mediatek.linkit.xml.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Packageinfo }
     * 
     */
    public Packageinfo createPackageinfo() {
        return new Packageinfo();
    }

    /**
     * Create an instance of {@link Packageinfo.Userinfo }
     * 
     */
    public Packageinfo.Userinfo createPackageinfoUserinfo() {
        return new Packageinfo.Userinfo();
    }

    /**
     * Create an instance of {@link Packageinfo.APIAuth }
     * 
     */
    public Packageinfo.APIAuth createPackageinfoAPIAuth() {
        return new Packageinfo.APIAuth();
    }

    /**
     * Create an instance of {@link Packageinfo.Targetconfig }
     * 
     */
    public Packageinfo.Targetconfig createPackageinfoTargetconfig() {
        return new Packageinfo.Targetconfig();
    }

    /**
     * Create an instance of {@link Packageinfo.Namelist }
     * 
     */
    public Packageinfo.Namelist createPackageinfoNamelist() {
        return new Packageinfo.Namelist();
    }

    /**
     * Create an instance of {@link Packageinfo.Operationinfo }
     * 
     */
    public Packageinfo.Operationinfo createPackageinfoOperationinfo() {
        return new Packageinfo.Operationinfo();
    }

    /**
     * Create an instance of {@link Packageinfo.Paymentlib }
     * 
     */
    public Packageinfo.Paymentlib createPackageinfoPaymentlib() {
        return new Packageinfo.Paymentlib();
    }

    /**
     * Create an instance of {@link Packageinfo.Output }
     * 
     */
    public Packageinfo.Output createPackageinfoOutput() {
        return new Packageinfo.Output();
    }

    /**
     * Create an instance of {@link Packageinfo.Resolution }
     * 
     */
    public Packageinfo.Resolution createPackageinfoResolution() {
        return new Packageinfo.Resolution();
    }

    /**
     * Create an instance of {@link Packageinfo.Vxp }
     * 
     */
    public Packageinfo.Vxp createPackageinfoVxp() {
        return new Packageinfo.Vxp();
    }

    /**
     * Create an instance of {@link Packageinfo.Font }
     * 
     */
    public Packageinfo.Font createPackageinfoFont() {
        return new Packageinfo.Font();
    }

    /**
     * Create an instance of {@link Packageinfo.Icon }
     * 
     */
    public Packageinfo.Icon createPackageinfoIcon() {
        return new Packageinfo.Icon();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mem", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<BigInteger> createPackageinfoTargetconfigMem(BigInteger value) {
        return new JAXBElement<BigInteger>(_PackageinfoTargetconfigMem_QNAME, BigInteger.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "supportbg", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigSupportbg(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigSupportbg_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userfont", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigUserfont(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigUserfont_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "screenrotate", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigScreenrotate(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigScreenrotate_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autoadaptable", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigAutoadaptable(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigAutoadaptable_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "usesysmemory", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigUsesysmemory(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigUsesysmemory_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sysdisk", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigSysdisk(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigSysdisk_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Push", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigPush(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigPush_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PushID", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<BigInteger> createPackageinfoTargetconfigPushID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PackageinfoTargetconfigPushID_QNAME, BigInteger.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PushSenderID", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigPushSenderID(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigPushSenderID_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autostart", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigAutostart(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigAutostart_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransferImg", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigTransferImg(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigTransferImg_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idleshortcut", scope = Packageinfo.Targetconfig.class)
    public JAXBElement<String> createPackageinfoTargetconfigIdleshortcut(String value) {
        return new JAXBElement<String>(_PackageinfoTargetconfigIdleshortcut_QNAME, String.class, Packageinfo.Targetconfig.class, value);
    }

}
