//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 10:04:40 PM CEST 
//


package se.aceone.mediatek.linkit.xml.config;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="userinfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="developer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="appname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="appversion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="appid" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="iconName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="APIAuth"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="defaultliblist" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="targetconfig"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="mem" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="supportbg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userfont" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="screenrotate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="autoadaptable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="usesysmemory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sysdisk" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Push" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PushID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="PushSenderID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="autostart" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TransferImg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="idleshortcut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="namelist"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="english" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="chinese" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="cht" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="operationinfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="imsi" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="paymentlib"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="smskey" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="output"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="device" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="resolution"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vxp"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="mreversion" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="sdkversion" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="venus" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="iot_wearable" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="font"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="icon"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userinfo",
    "apiAuth",
    "targetconfig",
    "namelist",
    "operationinfo",
    "paymentlib",
    "output",
    "resolution",
    "vxp",
    "font",
    "image",
    "icon"
})
@XmlRootElement(name = "packageinfo")
public class Packageinfo {

    @XmlElement(required = true)
    protected Packageinfo.Userinfo userinfo;
    @XmlElement(name = "APIAuth", required = true)
    protected Packageinfo.APIAuth apiAuth;
    @XmlElement(required = true)
    protected Packageinfo.Targetconfig targetconfig;
    @XmlElement(required = true)
    protected Packageinfo.Namelist namelist;
    @XmlElement(required = true)
    protected Packageinfo.Operationinfo operationinfo;
    @XmlElement(required = true)
    protected Packageinfo.Paymentlib paymentlib;
    @XmlElement(required = true)
    protected Packageinfo.Output output;
    @XmlElement(required = true)
    protected Packageinfo.Resolution resolution;
    @XmlElement(required = true)
    protected Packageinfo.Vxp vxp;
    @XmlElement(required = true)
    protected Packageinfo.Font font;
    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected Packageinfo.Icon icon;

    /**
     * Gets the value of the userinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Userinfo }
     *     
     */
    public Packageinfo.Userinfo getUserinfo() {
        return userinfo;
    }

    /**
     * Sets the value of the userinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Userinfo }
     *     
     */
    public void setUserinfo(Packageinfo.Userinfo value) {
        this.userinfo = value;
    }

    /**
     * Gets the value of the apiAuth property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.APIAuth }
     *     
     */
    public Packageinfo.APIAuth getAPIAuth() {
        return apiAuth;
    }

    /**
     * Sets the value of the apiAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.APIAuth }
     *     
     */
    public void setAPIAuth(Packageinfo.APIAuth value) {
        this.apiAuth = value;
    }

    /**
     * Gets the value of the targetconfig property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Targetconfig }
     *     
     */
    public Packageinfo.Targetconfig getTargetconfig() {
        return targetconfig;
    }

    /**
     * Sets the value of the targetconfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Targetconfig }
     *     
     */
    public void setTargetconfig(Packageinfo.Targetconfig value) {
        this.targetconfig = value;
    }

    /**
     * Gets the value of the namelist property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Namelist }
     *     
     */
    public Packageinfo.Namelist getNamelist() {
        return namelist;
    }

    /**
     * Sets the value of the namelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Namelist }
     *     
     */
    public void setNamelist(Packageinfo.Namelist value) {
        this.namelist = value;
    }

    /**
     * Gets the value of the operationinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Operationinfo }
     *     
     */
    public Packageinfo.Operationinfo getOperationinfo() {
        return operationinfo;
    }

    /**
     * Sets the value of the operationinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Operationinfo }
     *     
     */
    public void setOperationinfo(Packageinfo.Operationinfo value) {
        this.operationinfo = value;
    }

    /**
     * Gets the value of the paymentlib property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Paymentlib }
     *     
     */
    public Packageinfo.Paymentlib getPaymentlib() {
        return paymentlib;
    }

    /**
     * Sets the value of the paymentlib property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Paymentlib }
     *     
     */
    public void setPaymentlib(Packageinfo.Paymentlib value) {
        this.paymentlib = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Output }
     *     
     */
    public Packageinfo.Output getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Output }
     *     
     */
    public void setOutput(Packageinfo.Output value) {
        this.output = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Resolution }
     *     
     */
    public Packageinfo.Resolution getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Resolution }
     *     
     */
    public void setResolution(Packageinfo.Resolution value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the vxp property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Vxp }
     *     
     */
    public Packageinfo.Vxp getVxp() {
        return vxp;
    }

    /**
     * Sets the value of the vxp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Vxp }
     *     
     */
    public void setVxp(Packageinfo.Vxp value) {
        this.vxp = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Font }
     *     
     */
    public Packageinfo.Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Font }
     *     
     */
    public void setFont(Packageinfo.Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link Packageinfo.Icon }
     *     
     */
    public Packageinfo.Icon getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packageinfo.Icon }
     *     
     */
    public void setIcon(Packageinfo.Icon value) {
        this.icon = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="defaultliblist" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "defaultliblist"
    })
    public static class APIAuth {

        protected List<String> category;
        @XmlElement(required = true)
        protected String defaultliblist;

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCategory() {
            if (category == null) {
                category = new ArrayList<String>();
            }
            return this.category;
        }

        /**
         * Gets the value of the defaultliblist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultliblist() {
            return defaultliblist;
        }

        /**
         * Sets the value of the defaultliblist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultliblist(String value) {
            this.defaultliblist = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size"
    })
    public static class Font {

        @XmlElement(required = true)
        protected BigInteger size;

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSize(BigInteger value) {
            this.size = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "path"
    })
    public static class Icon {

        @XmlElement(required = true)
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="english" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="chinese" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="cht" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "english",
        "chinese",
        "cht"
    })
    public static class Namelist {

        @XmlElement(required = true)
        protected String english;
        @XmlElement(required = true)
        protected String chinese;
        @XmlElement(required = true)
        protected String cht;

        /**
         * Gets the value of the english property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnglish() {
            return english;
        }

        /**
         * Sets the value of the english property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnglish(String value) {
            this.english = value;
        }

        /**
         * Gets the value of the chinese property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChinese() {
            return chinese;
        }

        /**
         * Sets the value of the chinese property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChinese(String value) {
            this.chinese = value;
        }

        /**
         * Gets the value of the cht property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCht() {
            return cht;
        }

        /**
         * Sets the value of the cht property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCht(String value) {
            this.cht = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="imsi" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content",
        "imsi"
    })
    public static class Operationinfo {

        @XmlElement(required = true)
        protected String content;
        protected int imsi;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the imsi property.
         * 
         */
        public int getImsi() {
            return imsi;
        }

        /**
         * Sets the value of the imsi property.
         * 
         */
        public void setImsi(int value) {
            this.imsi = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="device" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "device"
    })
    public static class Output {

        @XmlElement(required = true)
        protected BigInteger type;
        @XmlElement(required = true)
        protected BigInteger device;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setType(BigInteger value) {
            this.type = value;
        }

        /**
         * Gets the value of the device property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDevice() {
            return device;
        }

        /**
         * Sets the value of the device property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDevice(BigInteger value) {
            this.device = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="smskey" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "smskey"
    })
    public static class Paymentlib {

        @XmlElement(required = true)
        protected String version;
        protected int smskey;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the smskey property.
         * 
         */
        public int getSmskey() {
            return smskey;
        }

        /**
         * Sets the value of the smskey property.
         * 
         */
        public void setSmskey(int value) {
            this.smskey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "width",
        "height"
    })
    public static class Resolution {

        @XmlElement(name = "Width", required = true)
        protected BigInteger width;
        @XmlElement(name = "Height", required = true)
        protected BigInteger height;

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWidth(BigInteger value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setHeight(BigInteger value) {
            this.height = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="mem" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="supportbg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="userfont" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="screenrotate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="autoadaptable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="usesysmemory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sysdisk" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Push" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PushID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="PushSenderID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="autostart" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TransferImg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="idleshortcut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memOrSupportbgOrUserfont"
    })
    public static class Targetconfig {

        @XmlElementRefs({
            @XmlElementRef(name = "Push", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "sysdisk", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "autostart", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "TransferImg", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "autoadaptable", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "usesysmemory", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "PushSenderID", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "PushID", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "idleshortcut", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mem", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "userfont", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "supportbg", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "screenrotate", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<? extends Serializable>> memOrSupportbgOrUserfont;

        /**
         * Gets the value of the memOrSupportbgOrUserfont property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the memOrSupportbgOrUserfont property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMemOrSupportbgOrUserfont().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<? extends Serializable>> getMemOrSupportbgOrUserfont() {
            if (memOrSupportbgOrUserfont == null) {
                memOrSupportbgOrUserfont = new ArrayList<JAXBElement<? extends Serializable>>();
            }
            return this.memOrSupportbgOrUserfont;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="developer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="appname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="appversion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="appid" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="iconName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "developer",
        "appname",
        "appversion",
        "appid",
        "iconName"
    })
    public static class Userinfo {

        @XmlElement(required = true)
        protected String developer;
        @XmlElement(required = true)
        protected String appname;
        @XmlElement(required = true)
        protected String appversion;
        @XmlElement(required = true)
        protected BigInteger appid;
        @XmlElement(required = true)
        protected String iconName;

        /**
         * Gets the value of the developer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeveloper() {
            return developer;
        }

        /**
         * Sets the value of the developer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeveloper(String value) {
            this.developer = value;
        }

        /**
         * Gets the value of the appname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppname() {
            return appname;
        }

        /**
         * Sets the value of the appname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppname(String value) {
            this.appname = value;
        }

        /**
         * Gets the value of the appversion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppversion() {
            return appversion;
        }

        /**
         * Sets the value of the appversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppversion(String value) {
            this.appversion = value;
        }

        /**
         * Gets the value of the appid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAppid() {
            return appid;
        }

        /**
         * Sets the value of the appid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAppid(BigInteger value) {
            this.appid = value;
        }

        /**
         * Gets the value of the iconName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIconName() {
            return iconName;
        }

        /**
         * Sets the value of the iconName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIconName(String value) {
            this.iconName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="mreversion" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="sdkversion" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="venus" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="iot_wearable" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mreversion",
        "sdkversion",
        "venus",
        "iotWearable"
    })
    public static class Vxp {

        protected BigInteger mreversion;
        protected BigInteger sdkversion;
        protected BigInteger venus;
        @XmlElement(name = "iot_wearable")
        protected BigInteger iotWearable;

        /**
         * Gets the value of the mreversion property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMreversion() {
            return mreversion;
        }

        /**
         * Sets the value of the mreversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMreversion(BigInteger value) {
            this.mreversion = value;
        }

        /**
         * Gets the value of the sdkversion property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSdkversion() {
            return sdkversion;
        }

        /**
         * Sets the value of the sdkversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSdkversion(BigInteger value) {
            this.sdkversion = value;
        }

        /**
         * Gets the value of the venus property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVenus() {
            return venus;
        }

        /**
         * Sets the value of the venus property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVenus(BigInteger value) {
            this.venus = value;
        }

        /**
         * Gets the value of the iotWearable property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIotWearable() {
            return iotWearable;
        }

        /**
         * Sets the value of the iotWearable property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIotWearable(BigInteger value) {
            this.iotWearable = value;
        }

    }

}
