//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 02:17:09 PM CEST 
//


package se.aceone.mediatek.linkit.xml.proj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.aceone.mediatek.linkit.xml.proj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.aceone.mediatek.linkit.xml.proj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VisualStudioProject }
     * 
     */
    public VisualStudioProject createVisualStudioProject() {
        return new VisualStudioProject();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Files }
     * 
     */
    public VisualStudioProject.Files createVisualStudioProjectFiles() {
        return new VisualStudioProject.Files();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Files.Filter }
     * 
     */
    public VisualStudioProject.Files.Filter createVisualStudioProjectFilesFilter() {
        return new VisualStudioProject.Files.Filter();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Configurations }
     * 
     */
    public VisualStudioProject.Configurations createVisualStudioProjectConfigurations() {
        return new VisualStudioProject.Configurations();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Configurations.Configuration }
     * 
     */
    public VisualStudioProject.Configurations.Configuration createVisualStudioProjectConfigurationsConfiguration() {
        return new VisualStudioProject.Configurations.Configuration();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Platforms }
     * 
     */
    public VisualStudioProject.Platforms createVisualStudioProjectPlatforms() {
        return new VisualStudioProject.Platforms();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Files.File }
     * 
     */
    public VisualStudioProject.Files.File createVisualStudioProjectFilesFile() {
        return new VisualStudioProject.Files.File();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Files.Filter.File }
     * 
     */
    public VisualStudioProject.Files.Filter.File createVisualStudioProjectFilesFilterFile() {
        return new VisualStudioProject.Files.Filter.File();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Configurations.Configuration.Tool }
     * 
     */
    public VisualStudioProject.Configurations.Configuration.Tool createVisualStudioProjectConfigurationsConfigurationTool() {
        return new VisualStudioProject.Configurations.Configuration.Tool();
    }

    /**
     * Create an instance of {@link VisualStudioProject.Platforms.Platform }
     * 
     */
    public VisualStudioProject.Platforms.Platform createVisualStudioProjectPlatformsPlatform() {
        return new VisualStudioProject.Platforms.Platform();
    }

}
