//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 12:01:34 PM CEST 
//


package se.aceone.mediatek.linkit.xml.proj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Platforms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Platform">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ToolFiles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Configurations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Configuration" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Tool" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="CommandLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="PreprocessorDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="MkTypLibCompatible" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="SuppressStartupBanner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="TargetEnvironment" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="TypeLibraryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="HeaderFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Optimization" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="AdditionalIncludeDirectories" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="MinimalRebuild" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="BasicRuntimeChecks" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="RuntimeLibrary" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="RuntimeTypeInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="PrecompiledHeaderFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="AssemblerListingLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ObjectFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ProgramDataBaseFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="BrowseInformation" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="WarningLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="DebugInformationFormat" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="ForcedIncludeFiles" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Culture" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                     &lt;attribute name="AdditionalDependencies" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="OutputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="LinkIncremental" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="IgnoreDefaultLibraryNames" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ModuleDefinitionFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="GenerateDebugInformation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ProgramDatabaseFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="SubSystem" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="RandomizedBaseAddress" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="DataExecutionPrevention" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="ImportLibrary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="TargetMachine" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="InlineFunctionExpansion" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="StringPooling" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="EnableFunctionLevelLinking" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="OutputDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="IntermediateDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ConfigurationType" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="InheritedPropertySheets" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="UseOfMFC" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="ATLMinimizesCRunTimeLibraryUsage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="CharacterSet" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="References" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Files">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Filter" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Filter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Globals" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ProjectType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ProjectGUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RootNamespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Keyword" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TargetFrameworkVersion" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "platforms",
    "toolFiles",
    "configurations",
    "references",
    "files",
    "globals"
})
@XmlRootElement(name = "VisualStudioProject")
public class VisualStudioProject {

    @XmlElement(name = "Platforms", required = true)
    protected VisualStudioProject.Platforms platforms;
    @XmlElement(name = "ToolFiles", required = true)
    protected String toolFiles;
    @XmlElement(name = "Configurations", required = true)
    protected VisualStudioProject.Configurations configurations;
    @XmlElement(name = "References", required = true)
    protected String references;
    @XmlElement(name = "Files", required = true)
    protected VisualStudioProject.Files files;
    @XmlElement(name = "Globals", required = true)
    protected String globals;
    @XmlAttribute(name = "ProjectType")
    protected String projectType;
    @XmlAttribute(name = "Version")
    protected String version;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "ProjectGUID")
    protected String projectGUID;
    @XmlAttribute(name = "RootNamespace")
    protected String rootNamespace;
    @XmlAttribute(name = "Keyword")
    protected String keyword;
    @XmlAttribute(name = "TargetFrameworkVersion")
    protected Byte targetFrameworkVersion;

    /**
     * Gets the value of the platforms property.
     * 
     * @return
     *     possible object is
     *     {@link VisualStudioProject.Platforms }
     *     
     */
    public VisualStudioProject.Platforms getPlatforms() {
        return platforms;
    }

    /**
     * Sets the value of the platforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualStudioProject.Platforms }
     *     
     */
    public void setPlatforms(VisualStudioProject.Platforms value) {
        this.platforms = value;
    }

    /**
     * Gets the value of the toolFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolFiles() {
        return toolFiles;
    }

    /**
     * Sets the value of the toolFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolFiles(String value) {
        this.toolFiles = value;
    }

    /**
     * Gets the value of the configurations property.
     * 
     * @return
     *     possible object is
     *     {@link VisualStudioProject.Configurations }
     *     
     */
    public VisualStudioProject.Configurations getConfigurations() {
        return configurations;
    }

    /**
     * Sets the value of the configurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualStudioProject.Configurations }
     *     
     */
    public void setConfigurations(VisualStudioProject.Configurations value) {
        this.configurations = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferences(String value) {
        this.references = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link VisualStudioProject.Files }
     *     
     */
    public VisualStudioProject.Files getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualStudioProject.Files }
     *     
     */
    public void setFiles(VisualStudioProject.Files value) {
        this.files = value;
    }

    /**
     * Gets the value of the globals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobals() {
        return globals;
    }

    /**
     * Sets the value of the globals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobals(String value) {
        this.globals = value;
    }

    /**
     * Gets the value of the projectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * Sets the value of the projectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectType(String value) {
        this.projectType = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the projectGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectGUID() {
        return projectGUID;
    }

    /**
     * Sets the value of the projectGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectGUID(String value) {
        this.projectGUID = value;
    }

    /**
     * Gets the value of the rootNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootNamespace() {
        return rootNamespace;
    }

    /**
     * Sets the value of the rootNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootNamespace(String value) {
        this.rootNamespace = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * Sets the value of the keyword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyword(String value) {
        this.keyword = value;
    }

    /**
     * Gets the value of the targetFrameworkVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTargetFrameworkVersion() {
        return targetFrameworkVersion;
    }

    /**
     * Sets the value of the targetFrameworkVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTargetFrameworkVersion(Byte value) {
        this.targetFrameworkVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Configuration" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Tool" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="CommandLine" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="PreprocessorDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MkTypLibCompatible" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="SuppressStartupBanner" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="TargetEnvironment" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="TypeLibraryName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="HeaderFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Optimization" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="AdditionalIncludeDirectories" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MinimalRebuild" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="BasicRuntimeChecks" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="RuntimeLibrary" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="RuntimeTypeInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="PrecompiledHeaderFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="AssemblerListingLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ObjectFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ProgramDataBaseFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="BrowseInformation" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="WarningLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="DebugInformationFormat" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="ForcedIncludeFiles" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Culture" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                           &lt;attribute name="AdditionalDependencies" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="OutputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="LinkIncremental" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="IgnoreDefaultLibraryNames" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ModuleDefinitionFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="GenerateDebugInformation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ProgramDatabaseFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="SubSystem" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="RandomizedBaseAddress" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="DataExecutionPrevention" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="ImportLibrary" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="TargetMachine" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="InlineFunctionExpansion" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="StringPooling" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="EnableFunctionLevelLinking" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="OutputDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="IntermediateDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ConfigurationType" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="InheritedPropertySheets" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="UseOfMFC" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="ATLMinimizesCRunTimeLibraryUsage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="CharacterSet" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "configuration"
    })
    public static class Configurations {

        @XmlElement(name = "Configuration")
        protected List<VisualStudioProject.Configurations.Configuration> configuration;

        /**
         * Gets the value of the configuration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the configuration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConfiguration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VisualStudioProject.Configurations.Configuration }
         * 
         * 
         */
        public List<VisualStudioProject.Configurations.Configuration> getConfiguration() {
            if (configuration == null) {
                configuration = new ArrayList<VisualStudioProject.Configurations.Configuration>();
            }
            return this.configuration;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Tool" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="CommandLine" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="PreprocessorDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MkTypLibCompatible" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="SuppressStartupBanner" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="TargetEnvironment" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="TypeLibraryName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="HeaderFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Optimization" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="AdditionalIncludeDirectories" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MinimalRebuild" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="BasicRuntimeChecks" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="RuntimeLibrary" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="RuntimeTypeInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="PrecompiledHeaderFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="AssemblerListingLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ObjectFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ProgramDataBaseFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="BrowseInformation" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="WarningLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="DebugInformationFormat" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="ForcedIncludeFiles" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Culture" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                 &lt;attribute name="AdditionalDependencies" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="OutputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="LinkIncremental" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="IgnoreDefaultLibraryNames" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ModuleDefinitionFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="GenerateDebugInformation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ProgramDatabaseFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="SubSystem" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="RandomizedBaseAddress" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="DataExecutionPrevention" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="ImportLibrary" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="TargetMachine" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="InlineFunctionExpansion" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="StringPooling" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="EnableFunctionLevelLinking" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="OutputDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="IntermediateDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ConfigurationType" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="InheritedPropertySheets" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="UseOfMFC" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="ATLMinimizesCRunTimeLibraryUsage" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="CharacterSet" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tool"
        })
        public static class Configuration {

            @XmlElement(name = "Tool")
            protected List<VisualStudioProject.Configurations.Configuration.Tool> tool;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "OutputDirectory")
            protected String outputDirectory;
            @XmlAttribute(name = "IntermediateDirectory")
            protected String intermediateDirectory;
            @XmlAttribute(name = "ConfigurationType")
            protected Byte configurationType;
            @XmlAttribute(name = "InheritedPropertySheets")
            protected String inheritedPropertySheets;
            @XmlAttribute(name = "UseOfMFC")
            protected Byte useOfMFC;
            @XmlAttribute(name = "ATLMinimizesCRunTimeLibraryUsage")
            protected String atlMinimizesCRunTimeLibraryUsage;
            @XmlAttribute(name = "CharacterSet")
            protected Byte characterSet;

            /**
             * Gets the value of the tool property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tool property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTool().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link VisualStudioProject.Configurations.Configuration.Tool }
             * 
             * 
             */
            public List<VisualStudioProject.Configurations.Configuration.Tool> getTool() {
                if (tool == null) {
                    tool = new ArrayList<VisualStudioProject.Configurations.Configuration.Tool>();
                }
                return this.tool;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the outputDirectory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutputDirectory() {
                return outputDirectory;
            }

            /**
             * Sets the value of the outputDirectory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutputDirectory(String value) {
                this.outputDirectory = value;
            }

            /**
             * Gets the value of the intermediateDirectory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIntermediateDirectory() {
                return intermediateDirectory;
            }

            /**
             * Sets the value of the intermediateDirectory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIntermediateDirectory(String value) {
                this.intermediateDirectory = value;
            }

            /**
             * Gets the value of the configurationType property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getConfigurationType() {
                return configurationType;
            }

            /**
             * Sets the value of the configurationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setConfigurationType(Byte value) {
                this.configurationType = value;
            }

            /**
             * Gets the value of the inheritedPropertySheets property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInheritedPropertySheets() {
                return inheritedPropertySheets;
            }

            /**
             * Sets the value of the inheritedPropertySheets property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInheritedPropertySheets(String value) {
                this.inheritedPropertySheets = value;
            }

            /**
             * Gets the value of the useOfMFC property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getUseOfMFC() {
                return useOfMFC;
            }

            /**
             * Sets the value of the useOfMFC property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setUseOfMFC(Byte value) {
                this.useOfMFC = value;
            }

            /**
             * Gets the value of the atlMinimizesCRunTimeLibraryUsage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getATLMinimizesCRunTimeLibraryUsage() {
                return atlMinimizesCRunTimeLibraryUsage;
            }

            /**
             * Sets the value of the atlMinimizesCRunTimeLibraryUsage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setATLMinimizesCRunTimeLibraryUsage(String value) {
                this.atlMinimizesCRunTimeLibraryUsage = value;
            }

            /**
             * Gets the value of the characterSet property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getCharacterSet() {
                return characterSet;
            }

            /**
             * Sets the value of the characterSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setCharacterSet(Byte value) {
                this.characterSet = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="CommandLine" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="PreprocessorDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MkTypLibCompatible" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="SuppressStartupBanner" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="TargetEnvironment" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="TypeLibraryName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="HeaderFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Optimization" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="AdditionalIncludeDirectories" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MinimalRebuild" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="BasicRuntimeChecks" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="RuntimeLibrary" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="RuntimeTypeInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="PrecompiledHeaderFile" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="AssemblerListingLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ObjectFile" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ProgramDataBaseFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="BrowseInformation" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="WarningLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="DebugInformationFormat" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="ForcedIncludeFiles" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Culture" type="{http://www.w3.org/2001/XMLSchema}short" />
             *       &lt;attribute name="AdditionalDependencies" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="OutputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="LinkIncremental" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="IgnoreDefaultLibraryNames" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ModuleDefinitionFile" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="GenerateDebugInformation" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ProgramDatabaseFile" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="SubSystem" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="RandomizedBaseAddress" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="DataExecutionPrevention" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="ImportLibrary" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="TargetMachine" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="InlineFunctionExpansion" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="StringPooling" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="EnableFunctionLevelLinking" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Tool {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Name")
                protected String name;
                @XmlAttribute(name = "CommandLine")
                protected String commandLine;
                @XmlAttribute(name = "PreprocessorDefinitions")
                protected String preprocessorDefinitions;
                @XmlAttribute(name = "MkTypLibCompatible")
                protected String mkTypLibCompatible;
                @XmlAttribute(name = "SuppressStartupBanner")
                protected String suppressStartupBanner;
                @XmlAttribute(name = "TargetEnvironment")
                protected Byte targetEnvironment;
                @XmlAttribute(name = "TypeLibraryName")
                protected String typeLibraryName;
                @XmlAttribute(name = "HeaderFileName")
                protected String headerFileName;
                @XmlAttribute(name = "Optimization")
                protected Byte optimization;
                @XmlAttribute(name = "AdditionalIncludeDirectories")
                protected String additionalIncludeDirectories;
                @XmlAttribute(name = "MinimalRebuild")
                protected String minimalRebuild;
                @XmlAttribute(name = "BasicRuntimeChecks")
                protected Byte basicRuntimeChecks;
                @XmlAttribute(name = "RuntimeLibrary")
                protected Byte runtimeLibrary;
                @XmlAttribute(name = "RuntimeTypeInfo")
                protected String runtimeTypeInfo;
                @XmlAttribute(name = "PrecompiledHeaderFile")
                protected String precompiledHeaderFile;
                @XmlAttribute(name = "AssemblerListingLocation")
                protected String assemblerListingLocation;
                @XmlAttribute(name = "ObjectFile")
                protected String objectFile;
                @XmlAttribute(name = "ProgramDataBaseFileName")
                protected String programDataBaseFileName;
                @XmlAttribute(name = "BrowseInformation")
                protected Byte browseInformation;
                @XmlAttribute(name = "WarningLevel")
                protected Byte warningLevel;
                @XmlAttribute(name = "DebugInformationFormat")
                protected Byte debugInformationFormat;
                @XmlAttribute(name = "ForcedIncludeFiles")
                protected String forcedIncludeFiles;
                @XmlAttribute(name = "Culture")
                protected Short culture;
                @XmlAttribute(name = "AdditionalDependencies")
                protected String additionalDependencies;
                @XmlAttribute(name = "OutputFile")
                protected String outputFile;
                @XmlAttribute(name = "LinkIncremental")
                protected Byte linkIncremental;
                @XmlAttribute(name = "IgnoreDefaultLibraryNames")
                protected String ignoreDefaultLibraryNames;
                @XmlAttribute(name = "ModuleDefinitionFile")
                protected String moduleDefinitionFile;
                @XmlAttribute(name = "GenerateDebugInformation")
                protected String generateDebugInformation;
                @XmlAttribute(name = "ProgramDatabaseFile")
                protected String programDatabaseFile;
                @XmlAttribute(name = "SubSystem")
                protected Byte subSystem;
                @XmlAttribute(name = "RandomizedBaseAddress")
                protected Byte randomizedBaseAddress;
                @XmlAttribute(name = "DataExecutionPrevention")
                protected Byte dataExecutionPrevention;
                @XmlAttribute(name = "ImportLibrary")
                protected String importLibrary;
                @XmlAttribute(name = "TargetMachine")
                protected Byte targetMachine;
                @XmlAttribute(name = "InlineFunctionExpansion")
                protected Byte inlineFunctionExpansion;
                @XmlAttribute(name = "StringPooling")
                protected String stringPooling;
                @XmlAttribute(name = "EnableFunctionLevelLinking")
                protected String enableFunctionLevelLinking;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the commandLine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCommandLine() {
                    return commandLine;
                }

                /**
                 * Sets the value of the commandLine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCommandLine(String value) {
                    this.commandLine = value;
                }

                /**
                 * Gets the value of the preprocessorDefinitions property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPreprocessorDefinitions() {
                    return preprocessorDefinitions;
                }

                /**
                 * Sets the value of the preprocessorDefinitions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPreprocessorDefinitions(String value) {
                    this.preprocessorDefinitions = value;
                }

                /**
                 * Gets the value of the mkTypLibCompatible property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMkTypLibCompatible() {
                    return mkTypLibCompatible;
                }

                /**
                 * Sets the value of the mkTypLibCompatible property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMkTypLibCompatible(String value) {
                    this.mkTypLibCompatible = value;
                }

                /**
                 * Gets the value of the suppressStartupBanner property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuppressStartupBanner() {
                    return suppressStartupBanner;
                }

                /**
                 * Sets the value of the suppressStartupBanner property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuppressStartupBanner(String value) {
                    this.suppressStartupBanner = value;
                }

                /**
                 * Gets the value of the targetEnvironment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getTargetEnvironment() {
                    return targetEnvironment;
                }

                /**
                 * Sets the value of the targetEnvironment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setTargetEnvironment(Byte value) {
                    this.targetEnvironment = value;
                }

                /**
                 * Gets the value of the typeLibraryName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTypeLibraryName() {
                    return typeLibraryName;
                }

                /**
                 * Sets the value of the typeLibraryName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTypeLibraryName(String value) {
                    this.typeLibraryName = value;
                }

                /**
                 * Gets the value of the headerFileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHeaderFileName() {
                    return headerFileName;
                }

                /**
                 * Sets the value of the headerFileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHeaderFileName(String value) {
                    this.headerFileName = value;
                }

                /**
                 * Gets the value of the optimization property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getOptimization() {
                    return optimization;
                }

                /**
                 * Sets the value of the optimization property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setOptimization(Byte value) {
                    this.optimization = value;
                }

                /**
                 * Gets the value of the additionalIncludeDirectories property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAdditionalIncludeDirectories() {
                    return additionalIncludeDirectories;
                }

                /**
                 * Sets the value of the additionalIncludeDirectories property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAdditionalIncludeDirectories(String value) {
                    this.additionalIncludeDirectories = value;
                }

                /**
                 * Gets the value of the minimalRebuild property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinimalRebuild() {
                    return minimalRebuild;
                }

                /**
                 * Sets the value of the minimalRebuild property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinimalRebuild(String value) {
                    this.minimalRebuild = value;
                }

                /**
                 * Gets the value of the basicRuntimeChecks property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getBasicRuntimeChecks() {
                    return basicRuntimeChecks;
                }

                /**
                 * Sets the value of the basicRuntimeChecks property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setBasicRuntimeChecks(Byte value) {
                    this.basicRuntimeChecks = value;
                }

                /**
                 * Gets the value of the runtimeLibrary property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getRuntimeLibrary() {
                    return runtimeLibrary;
                }

                /**
                 * Sets the value of the runtimeLibrary property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setRuntimeLibrary(Byte value) {
                    this.runtimeLibrary = value;
                }

                /**
                 * Gets the value of the runtimeTypeInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRuntimeTypeInfo() {
                    return runtimeTypeInfo;
                }

                /**
                 * Sets the value of the runtimeTypeInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRuntimeTypeInfo(String value) {
                    this.runtimeTypeInfo = value;
                }

                /**
                 * Gets the value of the precompiledHeaderFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrecompiledHeaderFile() {
                    return precompiledHeaderFile;
                }

                /**
                 * Sets the value of the precompiledHeaderFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrecompiledHeaderFile(String value) {
                    this.precompiledHeaderFile = value;
                }

                /**
                 * Gets the value of the assemblerListingLocation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAssemblerListingLocation() {
                    return assemblerListingLocation;
                }

                /**
                 * Sets the value of the assemblerListingLocation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAssemblerListingLocation(String value) {
                    this.assemblerListingLocation = value;
                }

                /**
                 * Gets the value of the objectFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getObjectFile() {
                    return objectFile;
                }

                /**
                 * Sets the value of the objectFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setObjectFile(String value) {
                    this.objectFile = value;
                }

                /**
                 * Gets the value of the programDataBaseFileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProgramDataBaseFileName() {
                    return programDataBaseFileName;
                }

                /**
                 * Sets the value of the programDataBaseFileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProgramDataBaseFileName(String value) {
                    this.programDataBaseFileName = value;
                }

                /**
                 * Gets the value of the browseInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getBrowseInformation() {
                    return browseInformation;
                }

                /**
                 * Sets the value of the browseInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setBrowseInformation(Byte value) {
                    this.browseInformation = value;
                }

                /**
                 * Gets the value of the warningLevel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getWarningLevel() {
                    return warningLevel;
                }

                /**
                 * Sets the value of the warningLevel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setWarningLevel(Byte value) {
                    this.warningLevel = value;
                }

                /**
                 * Gets the value of the debugInformationFormat property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getDebugInformationFormat() {
                    return debugInformationFormat;
                }

                /**
                 * Sets the value of the debugInformationFormat property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setDebugInformationFormat(Byte value) {
                    this.debugInformationFormat = value;
                }

                /**
                 * Gets the value of the forcedIncludeFiles property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getForcedIncludeFiles() {
                    return forcedIncludeFiles;
                }

                /**
                 * Sets the value of the forcedIncludeFiles property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setForcedIncludeFiles(String value) {
                    this.forcedIncludeFiles = value;
                }

                /**
                 * Gets the value of the culture property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getCulture() {
                    return culture;
                }

                /**
                 * Sets the value of the culture property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setCulture(Short value) {
                    this.culture = value;
                }

                /**
                 * Gets the value of the additionalDependencies property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAdditionalDependencies() {
                    return additionalDependencies;
                }

                /**
                 * Sets the value of the additionalDependencies property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAdditionalDependencies(String value) {
                    this.additionalDependencies = value;
                }

                /**
                 * Gets the value of the outputFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOutputFile() {
                    return outputFile;
                }

                /**
                 * Sets the value of the outputFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOutputFile(String value) {
                    this.outputFile = value;
                }

                /**
                 * Gets the value of the linkIncremental property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getLinkIncremental() {
                    return linkIncremental;
                }

                /**
                 * Sets the value of the linkIncremental property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setLinkIncremental(Byte value) {
                    this.linkIncremental = value;
                }

                /**
                 * Gets the value of the ignoreDefaultLibraryNames property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIgnoreDefaultLibraryNames() {
                    return ignoreDefaultLibraryNames;
                }

                /**
                 * Sets the value of the ignoreDefaultLibraryNames property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIgnoreDefaultLibraryNames(String value) {
                    this.ignoreDefaultLibraryNames = value;
                }

                /**
                 * Gets the value of the moduleDefinitionFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModuleDefinitionFile() {
                    return moduleDefinitionFile;
                }

                /**
                 * Sets the value of the moduleDefinitionFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModuleDefinitionFile(String value) {
                    this.moduleDefinitionFile = value;
                }

                /**
                 * Gets the value of the generateDebugInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGenerateDebugInformation() {
                    return generateDebugInformation;
                }

                /**
                 * Sets the value of the generateDebugInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGenerateDebugInformation(String value) {
                    this.generateDebugInformation = value;
                }

                /**
                 * Gets the value of the programDatabaseFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProgramDatabaseFile() {
                    return programDatabaseFile;
                }

                /**
                 * Sets the value of the programDatabaseFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProgramDatabaseFile(String value) {
                    this.programDatabaseFile = value;
                }

                /**
                 * Gets the value of the subSystem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getSubSystem() {
                    return subSystem;
                }

                /**
                 * Sets the value of the subSystem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setSubSystem(Byte value) {
                    this.subSystem = value;
                }

                /**
                 * Gets the value of the randomizedBaseAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getRandomizedBaseAddress() {
                    return randomizedBaseAddress;
                }

                /**
                 * Sets the value of the randomizedBaseAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setRandomizedBaseAddress(Byte value) {
                    this.randomizedBaseAddress = value;
                }

                /**
                 * Gets the value of the dataExecutionPrevention property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getDataExecutionPrevention() {
                    return dataExecutionPrevention;
                }

                /**
                 * Sets the value of the dataExecutionPrevention property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setDataExecutionPrevention(Byte value) {
                    this.dataExecutionPrevention = value;
                }

                /**
                 * Gets the value of the importLibrary property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getImportLibrary() {
                    return importLibrary;
                }

                /**
                 * Sets the value of the importLibrary property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setImportLibrary(String value) {
                    this.importLibrary = value;
                }

                /**
                 * Gets the value of the targetMachine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getTargetMachine() {
                    return targetMachine;
                }

                /**
                 * Sets the value of the targetMachine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setTargetMachine(Byte value) {
                    this.targetMachine = value;
                }

                /**
                 * Gets the value of the inlineFunctionExpansion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getInlineFunctionExpansion() {
                    return inlineFunctionExpansion;
                }

                /**
                 * Sets the value of the inlineFunctionExpansion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setInlineFunctionExpansion(Byte value) {
                    this.inlineFunctionExpansion = value;
                }

                /**
                 * Gets the value of the stringPooling property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStringPooling() {
                    return stringPooling;
                }

                /**
                 * Sets the value of the stringPooling property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStringPooling(String value) {
                    this.stringPooling = value;
                }

                /**
                 * Gets the value of the enableFunctionLevelLinking property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEnableFunctionLevelLinking() {
                    return enableFunctionLevelLinking;
                }

                /**
                 * Sets the value of the enableFunctionLevelLinking property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEnableFunctionLevelLinking(String value) {
                    this.enableFunctionLevelLinking = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Filter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Filter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter",
        "file"
    })
    public static class Files {

        @XmlElement(name = "Filter")
        protected List<VisualStudioProject.Files.Filter> filter;
        @XmlElement(name = "File")
        protected List<VisualStudioProject.Files.File> file;

        /**
         * Gets the value of the filter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VisualStudioProject.Files.Filter }
         * 
         * 
         */
        public List<VisualStudioProject.Files.Filter> getFilter() {
            if (filter == null) {
                filter = new ArrayList<VisualStudioProject.Files.Filter>();
            }
            return this.filter;
        }

        /**
         * Gets the value of the file property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the file property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VisualStudioProject.Files.File }
         * 
         * 
         */
        public List<VisualStudioProject.Files.File> getFile() {
            if (file == null) {
                file = new ArrayList<VisualStudioProject.Files.File>();
            }
            return this.file;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class File {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "RelativePath")
            protected String relativePath;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the relativePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelativePath() {
                return relativePath;
            }

            /**
             * Sets the value of the relativePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelativePath(String value) {
                this.relativePath = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Filter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "file"
        })
        public static class Filter {

            @XmlElement(name = "File")
            protected List<VisualStudioProject.Files.Filter.File> file;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Filter")
            protected String filter;

            /**
             * Gets the value of the file property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the file property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFile().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link VisualStudioProject.Files.Filter.File }
             * 
             * 
             */
            public List<VisualStudioProject.Files.Filter.File> getFile() {
                if (file == null) {
                    file = new ArrayList<VisualStudioProject.Files.Filter.File>();
                }
                return this.file;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the filter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilter() {
                return filter;
            }

            /**
             * Sets the value of the filter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilter(String value) {
                this.filter = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="RelativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class File {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "RelativePath")
                protected String relativePath;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the relativePath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRelativePath() {
                    return relativePath;
                }

                /**
                 * Sets the value of the relativePath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRelativePath(String value) {
                    this.relativePath = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Platform">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "platform"
    })
    public static class Platforms {

        @XmlElement(name = "Platform", required = true)
        protected VisualStudioProject.Platforms.Platform platform;

        /**
         * Gets the value of the platform property.
         * 
         * @return
         *     possible object is
         *     {@link VisualStudioProject.Platforms.Platform }
         *     
         */
        public VisualStudioProject.Platforms.Platform getPlatform() {
            return platform;
        }

        /**
         * Sets the value of the platform property.
         * 
         * @param value
         *     allowed object is
         *     {@link VisualStudioProject.Platforms.Platform }
         *     
         */
        public void setPlatform(VisualStudioProject.Platforms.Platform value) {
            this.platform = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Platform {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name")
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
